// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRedisSetMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRedisSetMembers'](arg1, arg2, arg3);
}

export function AddRedisSortedSetMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRedisSortedSetMembers'](arg1, arg2, arg3);
}

export function BrowseTableRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BrowseTableRows'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildMongoStructureDiagram(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildMongoStructureDiagram'](arg1, arg2, arg3);
}

export function BuildSchemaDiagram(arg1, arg2) {
  return window['go']['main']['App']['BuildSchemaDiagram'](arg1, arg2);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CheckPortAvailable(arg1) {
  return window['go']['main']['App']['CheckPortAvailable'](arg1);
}

export function CheckProfilePortConflict(arg1) {
  return window['go']['main']['App']['CheckProfilePortConflict'](arg1);
}

export function CloseConnectionSession(arg1) {
  return window['go']['main']['App']['CloseConnectionSession'](arg1);
}

export function CloseMongoSession(arg1) {
  return window['go']['main']['App']['CloseMongoSession'](arg1);
}

export function CloseRedisSession(arg1) {
  return window['go']['main']['App']['CloseRedisSession'](arg1);
}

export function ConnectUsingSavedConnection(arg1) {
  return window['go']['main']['App']['ConnectUsingSavedConnection'](arg1);
}

export function CountMongoDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CountMongoDocuments'](arg1, arg2, arg3, arg4);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function CreateSnippet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSnippet'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteMongoDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteMongoDocuments'](arg1, arg2, arg3, arg4);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteQueryHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteQueryHistoryEntry'](arg1);
}

export function DeleteRedisKeys(arg1, arg2) {
  return window['go']['main']['App']['DeleteRedisKeys'](arg1, arg2);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DeleteTableRows(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteTableRows'](arg1, arg2, arg3, arg4);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function FindMongoDocuments(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FindMongoDocuments'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetConnectionString(arg1) {
  return window['go']['main']['App']['GetConnectionString'](arg1);
}

export function GetProfileStatus(arg1) {
  return window['go']['main']['App']['GetProfileStatus'](arg1);
}

export function GetRedisHash(arg1, arg2) {
  return window['go']['main']['App']['GetRedisHash'](arg1, arg2);
}

export function GetRedisKeyType(arg1, arg2) {
  return window['go']['main']['App']['GetRedisKeyType'](arg1, arg2);
}

export function GetRedisList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRedisList'](arg1, arg2, arg3, arg4);
}

export function GetRedisSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRedisSet'](arg1, arg2, arg3, arg4);
}

export function GetRedisSortedSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRedisSortedSet'](arg1, arg2, arg3, arg4);
}

export function GetRedisString(arg1, arg2) {
  return window['go']['main']['App']['GetRedisString'](arg1, arg2);
}

export function GetRedisTTL(arg1, arg2) {
  return window['go']['main']['App']['GetRedisTTL'](arg1, arg2);
}

export function InsertMongoDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertMongoDocument'](arg1, arg2, arg3, arg4);
}

export function InsertTableRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertTableRow'](arg1, arg2, arg3, arg4);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListForeignKeysForSession(arg1, arg2) {
  return window['go']['main']['App']['ListForeignKeysForSession'](arg1, arg2);
}

export function ListMongoCollections(arg1, arg2) {
  return window['go']['main']['App']['ListMongoCollections'](arg1, arg2);
}

export function ListMongoDatabases(arg1) {
  return window['go']['main']['App']['ListMongoDatabases'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListQueryHistory(arg1) {
  return window['go']['main']['App']['ListQueryHistory'](arg1);
}

export function ListSchemasForSession(arg1) {
  return window['go']['main']['App']['ListSchemasForSession'](arg1);
}

export function ListSnippets(arg1) {
  return window['go']['main']['App']['ListSnippets'](arg1);
}

export function ListTablesForSession(arg1, arg2) {
  return window['go']['main']['App']['ListTablesForSession'](arg1, arg2);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function OpenMongoConnection(arg1) {
  return window['go']['main']['App']['OpenMongoConnection'](arg1);
}

export function OpenRedisConnection(arg1) {
  return window['go']['main']['App']['OpenRedisConnection'](arg1);
}

export function ParseConnectionURL(arg1) {
  return window['go']['main']['App']['ParseConnectionURL'](arg1);
}

export function PersistRedisKey(arg1, arg2) {
  return window['go']['main']['App']['PersistRedisKey'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PushRedisList(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushRedisList'](arg1, arg2, arg3);
}

export function RemoveRedisSetMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveRedisSetMembers'](arg1, arg2, arg3);
}

export function RemoveRedisSortedSetMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveRedisSortedSetMembers'](arg1, arg2, arg3);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RenameRedisKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRedisKey'](arg1, arg2, arg3);
}

export function ResetServiceVolume(arg1) {
  return window['go']['main']['App']['ResetServiceVolume'](arg1);
}

export function RestartProfile(arg1) {
  return window['go']['main']['App']['RestartProfile'](arg1);
}

export function RunMultiStatementQuery(arg1, arg2) {
  return window['go']['main']['App']['RunMultiStatementQuery'](arg1, arg2);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SampleMongoDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SampleMongoDocuments'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function ScanRedisKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanRedisKeys'](arg1, arg2, arg3, arg4);
}

export function SetRedisHash(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisHash'](arg1, arg2, arg3);
}

export function SetRedisListElement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRedisListElement'](arg1, arg2, arg3, arg4);
}

export function SetRedisString(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisString'](arg1, arg2, arg3);
}

export function SetRedisTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisTTL'](arg1, arg2, arg3);
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StartStatusWatcher() {
  return window['go']['main']['App']['StartStatusWatcher']();
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function StopStatusWatcher() {
  return window['go']['main']['App']['StopStatusWatcher']();
}

export function SuggestFreePort(arg1) {
  return window['go']['main']['App']['SuggestFreePort'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateMongoDocument(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateMongoDocument'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSnippet(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateSnippet'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTableRow(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTableRow'](arg1, arg2, arg3, arg4, arg5, arg6);
}
