// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortAvailable(arg1) {
  return window['go']['main']['App']['CheckPortAvailable'](arg1);
}

export function CheckProfilePortConflict(arg1) {
  return window['go']['main']['App']['CheckProfilePortConflict'](arg1);
}

export function ConnectUsingSavedConnection(arg1) {
  return window['go']['main']['App']['ConnectUsingSavedConnection'](arg1);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function GetConnectionString(arg1) {
  return window['go']['main']['App']['GetConnectionString'](arg1);
}

export function GetProfileStatus(arg1) {
  return window['go']['main']['App']['GetProfileStatus'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ParseConnectionURL(arg1) {
  return window['go']['main']['App']['ParseConnectionURL'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ResetServiceVolume(arg1) {
  return window['go']['main']['App']['ResetServiceVolume'](arg1);
}

export function RestartProfile(arg1) {
  return window['go']['main']['App']['RestartProfile'](arg1);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StartStatusWatcher() {
  return window['go']['main']['App']['StartStatusWatcher']();
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function StopStatusWatcher() {
  return window['go']['main']['App']['StopStatusWatcher']();
}

export function SuggestFreePort(arg1) {
  return window['go']['main']['App']['SuggestFreePort'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
