// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {redis} from '../models';
import {migrations} from '../models';
import {dbengine} from '../models';
import {main} from '../models';
import {storage} from '../models';
import {time} from '../models';

export function AddRedisSetMembers(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function AddRedisSortedSetMembers(arg1:string,arg2:string,arg3:Array<redis.SortedSetMember>):Promise<void>;

export function ApplyMigrations(arg1:string):Promise<migrations.ApplyResult>;

export function BrowseTableRows(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<dbengine.QueryResult>;

export function BuildMongoStructureDiagram(arg1:string,arg2:string,arg3:number):Promise<string>;

export function BuildSchemaDiagram(arg1:string,arg2:string):Promise<string>;

export function CancelQuery(arg1:string):Promise<void>;

export function CheckPortAvailable(arg1:number):Promise<boolean>;

export function CheckProfilePortConflict(arg1:number):Promise<main.PortConflictInfo>;

export function CloseConnectionSession(arg1:string):Promise<void>;

export function CloseMongoSession(arg1:string):Promise<void>;

export function CloseRedisSession(arg1:string):Promise<void>;

export function ConnectUsingSavedConnection(arg1:number):Promise<main.ConnectionFormFields>;

export function CountMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function CreateMigrationFile(arg1:number,arg2:string):Promise<migrations.Migration>;

export function CreateProfile(arg1:string,arg2:Array<main.ServiceRequest>):Promise<main.ProfileSummary>;

export function CreateSnippet(arg1:string,arg2:storage.Engine,arg3:string,arg4:Array<string>,arg5:any):Promise<storage.Snippet>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteQueryHistoryEntry(arg1:number):Promise<void>;

export function DeleteRedisKeys(arg1:string,arg2:Array<string>):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function DeleteTableRows(arg1:string,arg2:string,arg3:string,arg4:Array<Record<string, any>>):Promise<Array<dbengine.StatementResult>>;

export function DuplicateProfile(arg1:number):Promise<main.ProfileSummary>;

export function EnsureMigrationsTable(arg1:string):Promise<void>;

export function ExportQueryResultAsCSV(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function ExportQueryResultAsJSON(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function ExportTableAsCSV(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportTableAsJSON(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportTableAsSQLDump(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FindMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<Record<string, any>>>;

export function GetConnectionString(arg1:number):Promise<string>;

export function GetProfileStatus(arg1:number):Promise<string>;

export function GetRedisHash(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetRedisKeyType(arg1:string,arg2:string):Promise<string>;

export function GetRedisList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<string>>;

export function GetRedisSet(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.RedisSetPage>;

export function GetRedisSortedSet(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<redis.SortedSetMember>>;

export function GetRedisString(arg1:string,arg2:string):Promise<string>;

export function GetRedisTTL(arg1:string,arg2:string):Promise<time.Duration>;

export function ImportFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ImportCommitResult>;

export function InsertMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function InsertTableRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;

export function ListAppliedMigrationVersions(arg1:string):Promise<Array<number>>;

export function ListConnections():Promise<Array<storage.Connection>>;

export function ListForeignKeysForSession(arg1:string,arg2:string):Promise<Array<dbengine.ForeignKey>>;

export function ListMigrations(arg1:number):Promise<Array<migrations.Migration>>;

export function ListMongoCollections(arg1:string,arg2:string):Promise<Array<string>>;

export function ListMongoDatabases(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<main.ProfileSummary>>;

export function ListQueryHistory(arg1:storage.QueryHistoryFilter):Promise<Array<storage.QueryHistoryEntry>>;

export function ListSchemasForSession(arg1:string):Promise<Array<string>>;

export function ListSnippets(arg1:main.SnippetFilter):Promise<Array<storage.Snippet>>;

export function ListTablesForSession(arg1:string,arg2:string):Promise<Array<dbengine.TableInfo>>;

export function OpenConnection(arg1:main.ConnectionFormFields):Promise<string>;

export function OpenMongoConnection(arg1:main.ConnectionFormFields):Promise<string>;

export function OpenRedisConnection(arg1:main.ConnectionFormFields):Promise<string>;

export function ParseConnectionURL(arg1:string):Promise<main.ConnectionFormFields>;

export function PersistRedisKey(arg1:string,arg2:string):Promise<void>;

export function PickImportFile():Promise<string>;

export function PickMigrationsFolder():Promise<string>;

export function Ping():Promise<string>;

export function PushRedisList(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RemoveRedisSetMembers(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RemoveRedisSortedSetMembers(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RenameProfile(arg1:number,arg2:string):Promise<main.ProfileSummary>;

export function RenameRedisKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetServiceVolume(arg1:number):Promise<void>;

export function RestartProfile(arg1:number):Promise<void>;

export function RollbackMigration(arg1:string):Promise<migrations.Migration>;

export function RunMultiStatementQuery(arg1:string,arg2:string):Promise<Array<dbengine.StatementResult>>;

export function RunQuery(arg1:string,arg2:string):Promise<dbengine.QueryResult>;

export function SampleMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<Record<string, any>>>;

export function SaveConnection(arg1:main.ConnectionFormFields,arg2:string):Promise<storage.Connection>;

export function ScanRedisKeys(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ScanKeysResult>;

export function SetConnectionMigrationsFolder(arg1:number,arg2:string):Promise<storage.Connection>;

export function SetRedisHash(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function SetRedisListElement(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetRedisString(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRedisTTL(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StartProfile(arg1:number):Promise<void>;

export function StartStatusWatcher():Promise<void>;

export function StopProfile(arg1:number):Promise<void>;

export function StopStatusWatcher():Promise<void>;

export function SuggestFreePort(arg1:number):Promise<number>;

export function TestConnection(arg1:main.ConnectionFormFields):Promise<void>;

export function UpdateMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateSnippet(arg1:number,arg2:string,arg3:storage.Engine,arg4:string,arg5:Array<string>,arg6:any):Promise<storage.Snippet>;

export function UpdateTableRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>,arg5:string,arg6:any):Promise<void>;

export function ValidateImportFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ImportValidationResult>;
