// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortAvailable(arg1) {
  return window['go']['main']['App']['CheckPortAvailable'](arg1);
}

export function CheckProfilePortConflict(arg1) {
  return window['go']['main']['App']['CheckProfilePortConflict'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function GetConnectionString(arg1) {
  return window['go']['main']['App']['GetConnectionString'](arg1);
}

export function GetProfileStatus(arg1) {
  return window['go']['main']['App']['GetProfileStatus'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RestartProfile(arg1) {
  return window['go']['main']['App']['RestartProfile'](arg1);
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function SuggestFreePort(arg1) {
  return window['go']['main']['App']['SuggestFreePort'](arg1);
}
