// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProfile(arg1:string):Promise<main.ProfileSummary>;

export function GetProfileStatus(arg1:number):Promise<string>;

export function ListProfiles():Promise<Array<main.ProfileSummary>>;

export function Ping():Promise<string>;

export function RestartProfile(arg1:number):Promise<void>;

export function StartProfile(arg1:number):Promise<void>;

export function StopProfile(arg1:number):Promise<void>;
