// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbengine} from '../models';
import {main} from '../models';
import {storage} from '../models';

export function BrowseTableRows(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<dbengine.QueryResult>;

export function BuildSchemaDiagram(arg1:string,arg2:string):Promise<string>;

export function CancelQuery(arg1:string):Promise<void>;

export function CheckPortAvailable(arg1:number):Promise<boolean>;

export function CheckProfilePortConflict(arg1:number):Promise<main.PortConflictInfo>;

export function CloseConnectionSession(arg1:string):Promise<void>;

export function CloseMongoSession(arg1:string):Promise<void>;

export function ConnectUsingSavedConnection(arg1:number):Promise<main.ConnectionFormFields>;

export function CountMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function CreateProfile(arg1:string,arg2:Array<main.ServiceRequest>):Promise<main.ProfileSummary>;

export function CreateSnippet(arg1:string,arg2:storage.Engine,arg3:string,arg4:Array<string>,arg5:any):Promise<storage.Snippet>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteQueryHistoryEntry(arg1:number):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function DeleteTableRows(arg1:string,arg2:string,arg3:string,arg4:Array<Record<string, any>>):Promise<Array<dbengine.StatementResult>>;

export function DuplicateProfile(arg1:number):Promise<main.ProfileSummary>;

export function FindMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<Record<string, any>>>;

export function GetConnectionString(arg1:number):Promise<string>;

export function GetProfileStatus(arg1:number):Promise<string>;

export function InsertMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function InsertTableRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;

export function ListConnections():Promise<Array<storage.Connection>>;

export function ListForeignKeysForSession(arg1:string,arg2:string):Promise<Array<dbengine.ForeignKey>>;

export function ListMongoCollections(arg1:string,arg2:string):Promise<Array<string>>;

export function ListMongoDatabases(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<main.ProfileSummary>>;

export function ListQueryHistory(arg1:storage.QueryHistoryFilter):Promise<Array<storage.QueryHistoryEntry>>;

export function ListSchemasForSession(arg1:string):Promise<Array<string>>;

export function ListSnippets(arg1:main.SnippetFilter):Promise<Array<storage.Snippet>>;

export function ListTablesForSession(arg1:string,arg2:string):Promise<Array<dbengine.TableInfo>>;

export function OpenConnection(arg1:main.ConnectionFormFields):Promise<string>;

export function OpenMongoConnection(arg1:main.ConnectionFormFields):Promise<string>;

export function ParseConnectionURL(arg1:string):Promise<main.ConnectionFormFields>;

export function Ping():Promise<string>;

export function RenameProfile(arg1:number,arg2:string):Promise<main.ProfileSummary>;

export function ResetServiceVolume(arg1:number):Promise<void>;

export function RestartProfile(arg1:number):Promise<void>;

export function RunMultiStatementQuery(arg1:string,arg2:string):Promise<Array<dbengine.StatementResult>>;

export function RunQuery(arg1:string,arg2:string):Promise<dbengine.QueryResult>;

export function SaveConnection(arg1:main.ConnectionFormFields,arg2:string):Promise<storage.Connection>;

export function StartProfile(arg1:number):Promise<void>;

export function StartStatusWatcher():Promise<void>;

export function StopProfile(arg1:number):Promise<void>;

export function StopStatusWatcher():Promise<void>;

export function SuggestFreePort(arg1:number):Promise<number>;

export function TestConnection(arg1:main.ConnectionFormFields):Promise<void>;

export function UpdateMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateSnippet(arg1:number,arg2:string,arg3:storage.Engine,arg4:string,arg5:Array<string>,arg6:any):Promise<storage.Snippet>;

export function UpdateTableRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>,arg5:string,arg6:any):Promise<void>;
